# ~/.tmux.conf

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'mrjones2014/smart-splits.nvim'

set -g @plugin 'ofirgall/tmux-window-name'

set -g @plugin 'kristijanhusak/tmux-simple-git-status'
set -g status-right "#{simple_git_status}"


set -sg escape-time 0
set -g xterm-keys on

# True color support modification
set-option -a terminal-features 'xterm-256color:RGB'

# Pass Alt+hjkl through to nvim for smart-splits resizing
bind -n M-h run-shell "~/.tmux/plugins/smart-splits.nvim/smart-splits.sh resize-left"
bind -n M-j run-shell "~/.tmux/plugins/smart-splits.nvim/smart-splits.sh resize-down"
bind -n M-k run-shell "~/.tmux/plugins/smart-splits.nvim/smart-splits.sh resize-up"
bind -n M-l run-shell "~/.tmux/plugins/smart-splits.nvim/smart-splits.sh resize-right"

# initialize TPM (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'

# Colors for active window
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour24,bold

set -g pane-border-format " #[fg=white,bg=#7F2680,bold]#{?pane_active, ᕕ( ᐛ )ᕗ active,}#[default]#[fg=colour240]#{?pane_active,,  (ಠ_ಠ) inactive } "

set -g status-style bg=colour24,fg=white

